"""equipment anomaly models

Revision ID: 29bd495726ca
Revises: 0023_line_name_korean
Create Date: 2026-07-16 15:07:23.852000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0024_equipment_anomaly_models'
down_revision: Union[str, None] = '0023_line_name_korean'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_anomaly_models',
    sa.Column('process_type', sa.String(length=50), nullable=False),
    sa.Column('window', sa.Integer(), nullable=False),
    sa.Column('stride', sa.Integer(), nullable=False),
    sa.Column('confirm_k', sa.Integer(), nullable=False),
    sa.Column('ewma_limit', sa.Float(), nullable=True),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('train_rows', sa.Integer(), nullable=False),
    sa.Column('fitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('process_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment_anomaly_models')
    # ### end Alembic commands ###
