"""anomaly per equipment calibration

Revision ID: c6ac28981773
Revises: 0025_anomaly_shadow_events
Create Date: 2026-07-16 21:55:33.431610

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0026_anomaly_calibration"
down_revision: str | None = "0025_anomaly_shadow_events"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "equipment_anomaly_calibrations",
        sa.Column("equipment_id", sa.String(length=50), nullable=False),
        sa.Column("ewma_limit", sa.Float(), nullable=False),
        sa.Column("train_windows", sa.Integer(), nullable=False),
        sa.Column(
            "calibrated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment_masters.equipment_id"],
        ),
        sa.PrimaryKeyConstraint("equipment_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("equipment_anomaly_calibrations")
    # ### end Alembic commands ###
