"""anomaly shadow events

Revision ID: db7dddcf9e18
Revises: 0024_equipment_anomaly_models
Create Date: 2026-07-16 15:25:26.436525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0025_anomaly_shadow_events'
down_revision: Union[str, None] = '0024_equipment_anomaly_models'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_anomaly_shadow_events',
    sa.Column('event_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('equipment_id', sa.String(length=50), nullable=False),
    sa.Column('metric', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('raised_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment_masters.equipment_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_anomaly_shadow_active', 'equipment_anomaly_shadow_events', ['equipment_id'], unique=False, postgresql_where=sa.text('cleared_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_anomaly_shadow_active', table_name='equipment_anomaly_shadow_events', postgresql_where=sa.text('cleared_at IS NULL'))
    op.drop_table('equipment_anomaly_shadow_events')
    # ### end Alembic commands ###
