"""anomaly var path

Revision ID: a4f1f4602236
Revises: 0028_notification_read_state
Create Date: 2026-07-20 16:52:09.062786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0029_anomaly_var_path'
down_revision: Union[str, None] = '0028_notification_read_state'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment_anomaly_models', sa.Column('var_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('equipment_anomaly_models', sa.Column('var_ewma_limit', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment_anomaly_models', 'var_ewma_limit')
    op.drop_column('equipment_anomaly_models', 'var_state')
    # ### end Alembic commands ###
